targets:
  $default:
    builders:
      swagger_dart_code_generator:
        options:
          input_folder: "lib/schemes/" # Where your openapi.yaml is
          output_folder: "lib/api/"
          # Combine oneOf into Freezed unions
          use_inheritance: true 
          with_converter: true